### ISSUE TITLE
Repo has been rehosted as https://github.com/yaml/yaml-libyaml-perl6

### ISSUE THREAD

**Issue by ingydotnet** [CurtTilmes/perl6-libyaml#4]
I gave push access to @CurtTilmes

The code will soon be split into YAML::LibYAML::Parser and
YAML::LibYAML::Emitter, and will be made to backend YAML.pm in the exact way
the Perl 5's YAML.pm is being set up.

@CurtTilmes can you get the
https://github.com/perl6/ecosystem/blob/master/META.list updated and retire the
old repo?

Cheers, Ingy

**Comment by CurtTilmes** [comment]
Moved over and made a few edits to refs to the repo.
